great:
  GREAT_PRINCIPAL_8:
    name: Principal 8'
    ranks:
    - rank: M1
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  GREAT_OCTAVE_4:
    name: Octave 4'
    ranks:
    - rank: M1
      transpose: 12
      velocity_min: 127
      velocity_max: 127
  GREAT_FIFTEENTH_2:
    name: Fifteenth 2'
    ranks:
    - rank: M1
      transpose: 24
      velocity_min: 127
      velocity_max: 127
  GREAT_PRINCIPAL_16:
    name: Principal 16'
    ranks:
    - rank: M1
      transpose: -12
      velocity_min: 127
      velocity_max: 127
  GREAT_FLUTE_8:
    name: Flute 8'
    ranks:
    - rank: W1
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  GREAT_FLUTE_4:
    name: Flute 4'
    ranks:
    - rank: W1
      transpose: 12
      velocity_min: 127
      velocity_max: 127
  GREAT_BOURDON_16:
    name: Bourdon 16'
    ranks:
    - rank: W2
      transpose: -12
      velocity_min: 127
      velocity_max: 127
  GREAT_BOURDON_8:
    name: Bourdon 8'
    ranks:
    - rank: W2
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  GREAT_MIXTURE:
    name: Mixture IV-V
    ranks:
    - rank: D_GREAT_MIXTURE
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  GREAT_TRUMPET_8:
    name: Trumpet 8'
    ranks:
    - rank: D_GREAT_TRUMPET
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  GREAT_CLARION_4:
    name: Clarion 4'
    ranks:
    - rank: D_GREAT_CLARION
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  GREAT_MONTRE_8:
    name: Montre 8'
    ranks:
    - rank: D_GREAT_MONTRE
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  GREAT_MONTRE_4:
    name: Montre 4'
    ranks:
    - rank: D_GREAT_MONTRE
      transpose: 12
      velocity_min: 127
      velocity_max: 127

swell:
  SWELL_SALICIONAL_8:
    name: Salicional 8'
    ranks:
    - rank: M4
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  SWELL_VOIX_CELESTE_8:
    name: Voix Celeste 8'
    ranks:
    - rank: M3
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  SWELL_SALICIONAL_4:
    name: Salicional 4'
    ranks:
    - rank: M4
      transpose: 12
      velocity_min: 127
      velocity_max: 127
  SWELL_DULCIANA_8:
    name: Dulciana 8'
    ranks:
    - rank: M2
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  SWELL_PICCOLO_2:
    name: High String / Piccolo 2'
    ranks:
    - rank: M5
      transpose: 24
      velocity_min: 127
      velocity_max: 127
  SWELL_GEDACKT_8:
    name: Gedackt 8'
    ranks:
    - rank: W2
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  SWELL_FLUTE_4:
    name: Flute 4'
    ranks:
    - rank: W2
      transpose: 12
      velocity_min: 127
      velocity_max: 127
  SWELL_FIFTEENTH_2:
    name: Fifteenth 2'
    ranks:
    - rank: D_SWELL_FIFTEENTH
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  SWELL_MIXTURE:
    name: Mixture III
    ranks:
    - rank: D_SWELL_MIXTURE
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  SWELL_OBOE_8:
    name: Oboe 8'
    ranks:
    - rank: D_SWELL_OBOE
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  SWELL_TRUMPET_8:
    name: Trumpet 8'
    ranks:
    - rank: D_SWELL_TRUMPET
      transpose: 0
      velocity_min: 127
      velocity_max: 127
choir:
  CHOIR_LIEBLICH_GEDACKT_8:
    name: Lieblich Gedackt 8'
    ranks:
    - rank: W2
      transpose: 0
      velocity_min: 127
      velocity_max: 127
    notes: Borrowed from W2 (enclosed, but borrowed to unenclosed Choir)
  CHOIR_FLUTE_4:
    name: Flute 4'
    ranks:
    - rank: W2
      transpose: 12
      velocity_min: 127
      velocity_max: 127
    notes: Borrowed from W2 (enclosed, but borrowed to unenclosed Choir)
  CHOIR_PICCOLO_2:
    name: Piccolo 2'
    ranks:
    - rank: M5
      transpose: 24
      velocity_min: 127
      velocity_max: 127
    notes: Borrowed from M5, but non-tremmed version
  CHOIR_NAZARD_2_2_3:
    name: Nazard 2-2/3'
    ranks:
    - rank: D_CHOIR_NAZARD
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  CHOIR_TIERCE_1_3_5:
    name: Tierce 1-3/5'
    ranks:
    - rank: D_CHOIR_TIERCE
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  CHOIR_LARIGOT_1_1_3:
    name: Larigot 1-1/3'
    ranks:
    - rank: D_CHOIR_LARIGOT
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  CHOIR_CYMBALE:
    name: Cymbale III
    ranks:
    - rank: D_CHOIR_CYMBALE
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  CHOIR_CLARINET_8:
    name: Clarinet 8'
    ranks:
    - rank: D_CHOIR_CLARINET
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  CHOIR_VOX_HUMANA_8:
    name: Vox Humana 8'
    ranks:
    - rank: D_CHOIR_VOX_HUMANA
      transpose: 0
      velocity_min: 127
      velocity_max: 127
pedal:
  PEDAL_BOURDON_16:
    name: Bourdon 16'
    ranks:
    - rank: W2
      transpose: -12
      velocity_min: 127
      velocity_max: 127
  PEDAL_BOURDON_8:
    name: Bourdon 8'
    ranks:
    - rank: W2
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  PEDAL_FLUTE_4:
    name: Flute 4'
    ranks:
    - rank: W2
      transpose: 12
      velocity_min: 127
      velocity_max: 127
  PEDAL_TIBIA_BASS_16:
    name: Tibia Bass 16'
    ranks:
    - rank: W3
      transpose: -12
      velocity_min: 127
      velocity_max: 127
  PEDAL_SUBBASS_16:
    name: Subbass 16'
    ranks:
    - rank: R1
      transpose: -12
      velocity_min: 127
      velocity_max: 127
  PEDAL_OPEN_FLUTE_8:
    name: Open Flute 8'
    ranks:
    - rank: W1
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  PEDAL_PRINCIPAL_8:
    name: Principal 8'
    ranks:
    - rank: M1
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  PEDAL_MIXTURE:
    name: Mixture IV
    ranks:
    - rank: D_PEDAL_MIXTURE
      transpose: 0
      velocity_min: 127
      velocity_max: 127
  PEDAL_TROMBONE_16:
    name: Trombone 16'
    ranks:
    - rank: D_PEDAL_TROMBONE
      transpose: -12
      velocity_min: 127
      velocity_max: 127
  PEDAL_TRUMPET_8:
    name: Trumpet 8'
    ranks:
    - rank: D_PEDAL_TRUMPET
      transpose: 0
      velocity_min: 127
      velocity_max: 127
